mysql:
  url: dev-http://localhost:3306/db400
lagou:
  message: hello lagou,400
spring:
  mail:
    host: smtp.qq.com
    username: 164860244@qq.com
    password: pvydnvdnqbkabgff
    default-encoding: UTF-8
    port: 465
    properties:
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.debug: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou?useUnicode=true&characterEncoding=utf8
    username: root
    password:
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        #避免将驼峰命名转换为下划线命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl